version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: "mongo"
  bot:
    build: ./bot
    container_name: "bot"
    volumes: 
      - ./bot:/home/node/app
      - /home/node/app/node_modules
  backend:
    build: ./backend
    volumes: 
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    container_name: "backend"
  frontend:
    build: ./frontend
    volumes: 
      - ./frontend/build:/app/build
    ports:
      - "80:80"
    container_name: "frontend"